### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by EsioFreitas** [UnBArqDsw/2020.1_G3_RecipeBuk#15]
**Aspectos gerais** 
Olá! Muito legal a ideia do aplicativo! A paleta e logo estão bem legais. Além disso, as ideias do plano de custo e modelagem da metodologias foi iniciativas muito legais tbm. Parabéns. No entanto, sinto falta dos documentos de engenharia de requisitos, prototipagem e validação das ideias. Fiquem atentos a isso, pois a matéria vai exigindo mais dois alunos.

**Comment by juniopereirab** [comment]
Oi lindu, então.. Nossa documentação referente ao Design Sprint está pronta, e vamos organizar os documentos para subir para a Wiki em breve (tipo hoje ou amanhã rsrs)

**Comment by larissa-sales** [comment]
@EsioFreitas muito obrigada pelo feedback!!! Todos esses documentos (de requisitos, prototipagem e validação das ideias) estão sendo elaborados, quando finalizarmos estarão disponíveis na wiki!
